#!/bin/sh
# ~/.xinitrc - Start XFCE when running startx

# Source system xinitrc scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Start XFCE4
exec startxfce4
